# Generated by Django 5.0.6 on 2024-07-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourB_app', '0002_project_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
