# Generated by Django 5.0.6 on 2024-07-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveA_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
    ]
